### ISSUE TITLE
Header, Footer, Navigator bar

### ISSUE THREAD

**Issue by matcova337** [matcova337/Open-source#16]
# Thiết kế giao diện 
- Header
- Footer
- Navigator Bar
* Thiết kế trong 3 file php riêng biệt

**Comment by tiennennakenki** [comment]
> # Thiết kế giao diện
> * Header
> * Footer
> * Navigator Bar
> 
> * Thiết kế trong 3 file php riêng biệt

Phan Minh Tiến
